[package]
name = "mnemosyne-derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "mnemosyne_derive"
proc-macro = true

[features]
default = []

[dependencies]
quote = "1.0.35"
syn = "2.0.48"
proc-macro2 = "1.0.74"
